apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: frontend
  name: frontend
  namespace: <PROJECT NAMESPACE>
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - image: harbor.darwinapps.com/<PROJECT FRONTEND DOCKER IMAGE NAME>/frontend:latest
          name: frontend
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 200Mi
              cpu: "0.1"
      imagePullSecrets:
        - name: harbor-registry-secret
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: <PROJECT FRONTEND SERVICE NAME>
  namespace: <PROJECT NAMESPACE>
spec:
  selector:
    app.kubernetes.io/name: <PROJECT FRONTEND SERVICE NAME>
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP